name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [aarch64, x86_64]  # 定义 matrix 架构

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build \
          --build-arg ARCH=$ARCHITECTURE \
          --file Dockerfile \
          --tag my-image:${{ matrix.architecture }} .
      - name: Save amd64 image
        run: |
          docker save -o amd64_image.tar your-dockerhub-username/your-image-name:latest --platform linux/amd64

      - name: Save arm64 image
        run: |
          docker save -o arm64_image.tar your-dockerhub-username/your-image-name:latest --platform linux/arm64

      - name: Upload amd64 image
        uses: actions/upload-artifact@v2
        with:
          name: amd64_image
          path: amd64_image.tar

      - name: Upload arm64 image
        uses: actions/upload-artifact@v2
        with:
          name: arm64_image
          path: arm64_image.tar
