name: Build and Test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [aarch64, x86_64]  # 定义 matrix 架构

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build \
          --build-arg ARCH=${{ matrix.architecture }} \
          --build-arg BUILDKIT_MULTI_PLATFORM=1 \
          --file Dockerfile \
          --tag smartdns:${{ matrix.architecture }} .

    - name: Verify image architecture
      run: |
        image_tag="smartdns:${{ matrix.architecture }}"
        # 定义架构名称映射
        declare -A arch_map
        arch_map["x86_64"]="amd64"
        arch_map["aarch64"]="arm64"
        # 获取期望的架构，并进行映射
        expected_arch="${{ matrix.architecture }}" 
        if [[ ${arch_map[$expected_arch]} ]]; then
          expected_arch=${arch_map[$expected_arch]}
        fi
        # 使用 docker inspect 验证架构 (方法一)
        actual_arch=$(docker inspect --format='{{.Architecture}}' "$image_tag")
        if [ "$actual_arch" = "$expected_arch" ]; then
          echo "镜像架构验证成功：$actual_arch"
        else
          echo "镜像架构验证失败！期望：$expected_arch, 实际：$actual_arch"
          exit 1
        fi

    - name: Log into registry
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin

    - name: Save image
      run: |
          docker save -o smartdns_${{ matrix.architecture }}.tar smartdns:${{ matrix.architecture }}

    - name: Upload image
      uses: actions/upload-artifact@v4
      with:
          name: smartdns_${{ matrix.architecture }}_image
          path: smartdns_${{ matrix.architecture }}.tar

    - name: Create download link in summary
      if: ${{ github.event_name == 'workflow_dispatch' }} # 仅在手动触发时显示
      run: |
        echo "## Download SmartDNS Images" >> $GITHUB_STEP_SUMMARY
        echo "- [smartdns_${{ matrix.architecture }}](<tex>${{ steps.upload.outputs.artifact-path }})" >> $GITHUB_STEP_SUMMARY
