name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [aarch64, x86_64]  # 定义 matrix 架构

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build \
          --build-arg ARCH=${{ matrix.architecture }} \
          --build-arg BUILDKIT_MULTI_PLATFORM=1 \
          --file Dockerfile \
          --tag smartdns:${{ matrix.architecture }} .
          
    - name: Log into registry
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin

    - name: Save image
      run: |
          docker save -o smartdns_${{ matrix.architecture }}.tar smartdns:${{ matrix.architecture }}

    - name: Upload image
      uses: actions/upload-artifact@v4
      with:
          name: smartdns_${{ matrix.architecture }}_image
          path: smartdns_${{ matrix.architecture }}.tar

