name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [aarch64, x86_64]  # 定义 matrix 架构

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: 打印环境变量
      run: echo "MY_VARIABLE is $ARCHITECTURE, ${{ matrix.architecture }}"

    - name: Build Docker image
      run: |
        docker build \
          --build-arg ARCH=${{ matrix.architecture }} \
          --build-arg BUILDKIT_MULTI_PLATFORM=1 \
          --file Dockerfile \
          --tag smartdns:${{ matrix.architecture }} .
