name: Build and Test

on:
  push:
    branches:
      - smartdns
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        architecture: [aarch64, x86_64]  # 定义 matrix 架构

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Check Docker credentials
      run: |
        if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
          echo "DOCKER_USERNAME is not set"
        exit 1
        fi
        if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
          echo "DOCKERHUB_TOKEN is not set"
        exit 1
        fi
        echo "DOCKER_USERNAME and DOCKER_PASSWORD are set"

    - name: Log into registry
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin

    - name: Build and push multi-architecture image
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --file Dockerfile \
          --tag szqhan/smartdns:latest \
          . \
          --push
          

